In [2]:
import numpy as np 


In [5]:
a = np.random.randn(2,4,4)

np.sum(a, axis=(1,2))

array([-1.01286846,  8.0107237 ])

In [6]:
b = np.random.randn(4,4)

a*b

array([[[-2.23980577e-02,  5.03002752e-01, -5.13431950e-01,
         -1.08355254e+00],
        [-5.30829023e-01,  9.74644640e-04,  5.40129726e-01,
          4.21941723e-01],
        [ 7.22854227e-01,  1.09381727e+00,  1.47132588e+00,
          6.84438756e-01],
        [-1.08397915e-01,  1.51313882e+00, -4.67249003e-01,
         -4.27705131e-01]],

       [[ 3.09461554e-02, -1.03586711e+00,  6.77323427e-01,
          3.21965142e-01],
        [-1.52484504e-01,  7.44780021e-04,  1.65823841e-01,
          2.42976152e+00],
        [-5.09596317e-01, -1.04599727e+00,  6.24675742e-01,
          4.42355535e-01],
        [-1.88635765e+00,  1.02500553e+00,  5.26564305e-01,
          2.41091014e-01]]])

In [15]:
w = np.array(

   [
    [
        [
         [1,1],
         [1,1]
        ],

        [
         [2,2],
         [2,2]
        ],

        [
         [3,3],
         [3,3]
        ]
    ],
    
    [
        [
         [4,4],
         [4,4]
        ],

        [
         [5,5],
         [5,5]
        ],

        [
         [6,6],
         [6,6]
        ]
    ]
 ]

)


n_c, n_c_prev, f, f = np.shape(w)

w_ba = np.reshape(w, (n_c_prev*f*f, n_c))

w_ba

w_ba2 = np.reshape(w, (n_c,n_c_prev*f*f)).T

w_ba2

np.shape(w_ba2)



array([[1, 1],
       [1, 1],
       [2, 2],
       [2, 2],
       [3, 3],
       [3, 3],
       [4, 4],
       [4, 4],
       [5, 5],
       [5, 5],
       [6, 6],
       [6, 6]])

array([[1, 4],
       [1, 4],
       [1, 4],
       [1, 4],
       [2, 5],
       [2, 5],
       [2, 5],
       [2, 5],
       [3, 6],
       [3, 6],
       [3, 6],
       [3, 6]])

(12, 2)

array([[[[1, 1],
         [1, 1]],

        [[2, 2],
         [2, 2]],

        [[3, 3],
         [3, 3]]],


       [[[4, 4],
         [4, 4]],

        [[5, 5],
         [5, 5]],

        [[6, 6],
         [6, 6]]]])

In [22]:
w_tran = w.reshape(2*3,2,2)

w_tran

w_tran_tran = w_tran.reshape(2,3,2,2)

w_tran_tran 

array([[[1, 1],
        [1, 1]],

       [[2, 2],
        [2, 2]],

       [[3, 3],
        [3, 3]],

       [[4, 4],
        [4, 4]],

       [[5, 5],
        [5, 5]],

       [[6, 6],
        [6, 6]]])

array([[[[1, 1],
         [1, 1]],

        [[2, 2],
         [2, 2]],

        [[3, 3],
         [3, 3]]],


       [[[4, 4],
         [4, 4]],

        [[5, 5],
         [5, 5]],

        [[6, 6],
         [6, 6]]]])

In [27]:
w_tran = w.reshape((2*3,2,2))

w_tran

x = np.ones((6,2,2))

res = np.dot(w_tran,x)

# res

np.shape(res)

array([[[1, 1],
        [1, 1]],

       [[2, 2],
        [2, 2]],

       [[3, 3],
        [3, 3]],

       [[4, 4],
        [4, 4]],

       [[5, 5],
        [5, 5]],

       [[6, 6],
        [6, 6]]])

(6, 2, 6, 2)

In [31]:

w = np.ones((4,4))

p=1

w_pad = np.pad(w, ((p, p), (p, p)), 'constant', constant_values=0)

w_pad

w_pad[p:-p, p:-p]


array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:

x_ba = np.array([
         [1,1,2],
         [1,3,1],
         [1,3,4]
        ])

max_idx = np.argmax(x_ba,axis=1)

max_idx # array([2, 1, 2], dtype=int64)

x_ba[np.arange(3), max_idx] # array([2, 3, 4])


grad_x_ba = np.zeros((3,3))

grad_y_ba = np.array([1,2,3])


idx = np.array(list(zip(np.arange(3), max_idx)))
idx


grad_x_ba[np.arange(3), max_idx] = grad_y_ba

grad_x_ba

# for i in range( np.shape(idx)[0] ):
    
#     grad_x_ba[idx[i][0],idx[i][1]] = grad_y_ba[i]

# grad_x_ba




array([2, 1, 2], dtype=int64)

array([2, 3, 4])

array([[0, 2],
       [1, 1],
       [2, 2]], dtype=int64)

array([[0., 0., 1.],
       [0., 2., 0.],
       [0., 0., 3.]])

array([4, 3, 6])

In [76]:
x_ba.reshape(9)

array([1, 1, 2, 1, 3, 1, 1, 3, 4])

In [83]:
x=np.arange(16).reshape((4,4))

x

x[
    [0,1,2,3], # 行索引
    [1,2,3,0]  # 列索引
]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([ 1,  6, 11, 12])

In [91]:
a=np.ones((1,10))

b= np.ones((2,5))

res= np.dot(np.expand_dims(b, axis=2) ,a)

np.shape(res)

(2, 5, 10)

In [7]:

np.random.randn(2,3)

array([[-0.5207762 , -0.33773344, -0.46694969],
       [ 0.97370254,  1.61687661, -0.26832344]])

In [10]:

def process( a, **kwargs ):
    
    print(len(kwargs))

process(10, b=1,c=2,d=3)    


3


In [14]:
a = np.arange(16).reshape((4,4))

a

b = a.reshape((2,2,4))

b.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
import numpy as np 

np.random.seed(231)  # 控制随机数, 控制一次后效果消失

mask = np.random.randint(10, size=3)

# mask

In [35]:
mask2 = np.random.randint(10, size=3)

mask2

array([6, 3, 0])

In [37]:
0%6

0